---
title: "first_model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r pressure, echo=FALSE}
library(lubridate)
library(tidyverse)
library(R2jags)
```

## Data
```{r eval=FALSE}
pres_polls = read.csv("president_polls.csv")

pres_polls$days_to_election = as.numeric(as.Date(pres_polls$election_date, "%m/%d/%y")-as.Date(pres_polls$end_date, "%m/%d/%y"))
```

```{r}

econ_pres_polls = read.csv("2020 US presidential election polls - all_polls.csv")

econ_pres_polls$end.date = as.character(econ_pres_polls$end.date)

econ_pres_polls = econ_pres_polls %>%
  mutate(end.date = case_when(
    end.date == "108/2020" ~ "10/8/2020",
    TRUE ~ end.date
  ))

econ_pres_polls$days_to_election = as.numeric(as.Date("11/3/2020", "%m/%d/%y")-as.Date(econ_pres_polls$end.date, "%m/%d/%y"))

econ_pres_polls$state = as.character(econ_pres_polls$state)

econ_pres_polls = econ_pres_polls %>%
  filter(days_to_election <= 90) %>%
  mutate(state = ifelse(state == "--","US",state),
         y = biden/(biden + trump)*100)

#states_of_interest = c("VA", "MN", "NH", "MI", "WI", "PA", "NV", "FL", "AZ", "NC", "GA", "IA", "OH", "TX", "AK", "SC", "MO", "MT", "MS")

#econ_pres_polls= econ_pres_polls %>% filter(state %in% states_of_interest)

```

```{r}
states <- sort(econ_pres_polls$state %>% unique)

y <- econ_pres_polls$y
r <- match(econ_pres_polls$state,states)
t <- econ_pres_polls$days_to_election + 1 #WHY PLUS ONE?

N_polls <- y %>% length
N_states <- states %>% length
N_days <- t %>% max

jags_data <- list(y=y,t=t,r=r,
                  N_polls=N_polls,N_states=N_states,N_days=N_days)
```




```{r model,eval = TRUE}
model <- function(){
  
  for(k in 1:N_polls){
    y[k] ~ dnorm(p[k],1/sigma2_y[r[k]]) #note no longer binomial
    p[k] = beta[r[k],t[k]] 
  }
  
  for(j in 2:N_days){
    for(i in 1:N_states){
      beta[i,j] ~ dnorm(beta[i,j-1],pow(sigma2_beta[i],-1))
    }
  }

  # for(j in 2:N_days){
  #   for(i in 1:N_states){
  #     for (q in 1:100){
  #     #HOW TO GET POSTERIOR PRED DISTRIBUTION?
  #       betaq[i,j,q] ~ dnorm(beta[i,j-1],pow(sigma2_beta[i],-1))
  #       compare1[i,j,q] <- ifelse(betaq[i,j,q] > 50, 1, 0)
  #     }
  #    beta[i,j] ~ dnorm(beta[i,j-1],pow(sigma2_beta[i],-1))
  #    BidenWins[i,j] <- sum(compare1[i,j,])/100
  #   }
  # }
  #EXERCISE: add hierarchical prior for sigma2_beta and sigma2_y, i.e. sigma2_beta[j] all come from a common distribution 
  for (j in 1:N_states){
      sigma2_y[j] = 1/sigma2_y_inv[j]
      sigma2_y_inv[j] ~ dgamma(nu_y,nu_y*tau_y) 
      
      sigma2_beta[j] = 1/sigma2_beta_inv[j]
      sigma2_beta_inv[j] ~ dgamma(nu_beta,nu_beta*tau_beta) 
      
      beta[j,1] ~ dnorm(mu0,pow(sigma2_0,-1))
  }
  nu_y ~ dunif(0,100)
  tau_y ~ dunif(0,100)
  
  nu_beta ~ dunif(0,100)
  tau_beta ~ dunif(0,100)
  
  mu0 ~ dnorm(50,pow(7.5,-2))
  sigma2_0 = 1/sigma2_0_inv
  sigma2_0_inv ~ dgamma(.5,.5)
  
  
}
```

```{r run_model,eval=TRUE,cache=TRUE}

#be sure to add your added parameters to parameters.to.save
jags_sims <- jags(data = jags_data,model.file = model,parameters.to.save = c("beta","sigma2_beta","BidenWins",
                                                                             "p","sigma2_y"),
                  n.iter = 10000)


```

```{r eval=FALSE}
jags_sims$BUGSoutput

BidenWins <- jags_sims$BUGSoutput$sims.list$BidenWins[,,1]

hist(BidenWins)

print(c(quantile(BidenWins, 0.3), quantile(BidenWins, 0.7)))
```

## Not required: Probability of Biden Win by State

```{r}
elec_sims <- jags_sims$BUGSoutput$sims.list$beta[,,1]
colnames(elec_sims) <- states
(elec_sims>50) %>% colMeans() #P(Biden Win) each state

#in other states: Biden: 232-13, Trump: 306-29-18-15-10-20
#b_ex_votes <- 232-13; t_ex_votes <- 306-29-18-15-10-20
```

## Probability Trump Wins Re-Election

```{r}
ec_bystate = c(3, 9, 11, 55, 9, 3, 29, 16, 6, 4, 11, 6, 8, 8, 11, 10, 4, 16, 10, 10, 6, 3, 15, 3, 4, 14, 5, 6, 29, 18, 7, 7, 20, 9, 38, 0, 6, 11, 3, 12, 10, 5 )

ec_votes_inc_states <- ((elec_sims>50) %*% diag(ec_bystate)) %>% rowSums() #+ 232

ec_votes_dem = ec_votes_inc_states+7+4+20+4+3 #anything else Biden should win (CT, Hawaii, IL, RI, DC)

# anything else for Trump (6 Arkansas, 5 Nebraska, 11 Tennessee, 3 S Dakota, 3 Wyoming) 

p_trump_win = 1 - mean(ec_votes_dem >= 270)
p_trump_win
```

## More bonus stuff

```{r}
hist(ec_votes)

pmean = ec_votes>=270
mean(ec_votes>=270) 
print(c(quantile(pmean, 0.025), quantile(pmean, 0.975)))
```

```{r eval=FALSE}
house_polls = read.csv("house_polls.csv")
nc_house_polls = house_polls %>%
  filter(state == "North Carolina")
```

```{r eval=FALSE}
voter_small = readRDS("ncvoter_Statewide_small.rds")
hist_small = readRDS("ncvhis_Statewide_small.rds")
```
