---
title: "PPC_models"
author: "Lynn Fan"
date: "11/2/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r pressure, echo=FALSE, message=F, warning=F}
library(lubridate)
library(tidyverse)
library(R2jags)
library(gridExtra)
library(jagsUI)
```

## Data

```{r }

#pres_polls = read.csv("president_polls.csv")

pres_polls = read.csv("president_general_polls_2016.csv")

# dem_results = pres_polls[pres_polls$candidate_party == "DEM",]
# dem_cols = colnames(dem_results)
# cols_to_paste = (length(dem_cols)-3):length(dem_cols)
# dem_cols[cols_to_paste] = paste(dem_cols[cols_to_paste], "DEM", sep="_")
# colnames(dem_results) = dem_cols
# 
# rep_results = pres_polls[pres_polls$candidate_party == "REP",]
# rep_cols = colnames(rep_results)
# rep_cols[cols_to_paste] = paste(rep_cols[cols_to_paste], "REP", sep="_")
# colnames(rep_results) = rep_cols
# 
# rep_small = rep_results %>% select(question_id, candidate_id_REP, candidate_name_REP, pct_REP)
# 
# final_polls = left_join(dem_results, rep_small, by="question_id")

final_polls = pres_polls[!duplicated(pres_polls$poll_id),]

final_polls$days_to_election = as.numeric(as.Date("11/8/2016", "%m/%d/%y")-as.Date(final_polls$enddate, "%m/%d/%y"))

final_polls = final_polls %>% filter(days_to_election > 0)

#final_polls$state = as.character(final_polls$state)

final_polls$votes_DEM = round( (final_polls$rawpoll_clinton/100) * final_polls$samplesize)
final_polls$votes_REP = round( (final_polls$rawpoll_trump/100) * final_polls$samplesize)

final_polls = final_polls %>% mutate(y = votes_DEM/(votes_DEM + votes_REP)*100)


#final_polls = final_polls %>%
#  mutate(state = ifelse(state == "","US",state))

states_raw = read.csv("electoral_votes.csv")
states_raw$state = states_raw$State

final_polls = merge(final_polls, states_raw, by="state", all.x=T)
final_polls$Abbrev = as.character(final_polls$Abbrev)
final_polls$Abbrev = replace_na(final_polls$Abbrev, "U.S.")
final_polls$state = final_polls$Abbrev

econ_pres_polls = final_polls
#saveRDS(econ_pres_polls, "cleaned_pres_polls.rds")
```

```{r eval=F}

econ_pres_polls = read.csv("2020 US presidential election polls - all_polls.csv")

econ_pres_polls$end.date = as.character(econ_pres_polls$end.date)

econ_pres_polls = econ_pres_polls %>%
  mutate(end.date = case_when(
    end.date == "108/2020" ~ "10/8/2020",
    TRUE ~ end.date
  ))

econ_pres_polls$days_to_election = as.numeric(as.Date("11/3/2020", "%m/%d/%y")-as.Date(econ_pres_polls$end.date, "%m/%d/%y"))

econ_pres_polls$state = as.character(econ_pres_polls$state)

econ_pres_polls = econ_pres_polls %>%
  mutate(state = ifelse(state == "--","US",state),
         y = biden/(biden + trump)*100)

```

```{r}
econ_pres_polls = econ_pres_polls %>%
  filter(days_to_election <= 30)

states_of_interest = c("MN", "NH", "MI", "WI", "PA", "NV", "FL", "AZ", "NC", "GA", "IA", "OH", "TX")

econ_pres_polls= econ_pres_polls %>% filter(state %in% states_of_interest)
#saveRDS(econ_pres_polls, "cleaned_econ_polls.rds")
```

```{r}
states <- sort(econ_pres_polls$state %>% unique)

y <- econ_pres_polls$y
r <- match(econ_pres_polls$state,states)
t <- econ_pres_polls$days_to_election + 1 #WHY PLUS ONE?

N_polls <- y %>% length
N_states <- states %>% length
N_days <- t %>% max

# calculate partisan lean part of the prior
#leans_allstates = read.csv("partisan_leans.csv")
leans_allstates = read.csv("partisan_leans_538.csv")
leans_states = NULL
for (st in states) {
  new_lean = leans_allstates[leans_allstates$Abbrev==st, "Lean"]
  leans_states = c(leans_states, new_lean)
}

lean_to_prior = function(lean) {
  return(50 + (1/2)*lean)
}
abramowitz <- read.csv('abramowitz_additional.csv')
abramowitz = abramowitz %>% filter(year != 2016)
prior_model <- lm(incvote ~  juneapp + three_month_stock_growth + q2_real_income_growth, data = abramowitz)
national_mu_prior <- predict(prior_model,newdata = tibble(juneapp = 4, three_month_stock_growth = 0.003383248, q2_real_income_growth = 1.8))
```


```{r final-prior-calculation}
# because partisan lean is in terms of democ
priors = 0.1*national_mu_prior + 0.9*lean_to_prior(leans_states)

jags_data <- list(y=y,t=t,r=r,
                  N_polls=N_polls,N_states=N_states,N_days=N_days,
                  priors=priors)
```


# Model with multivariate formulation

# BORROWED FROM https://rdrr.io/cran/jagsUI/man/ppcheck.html

```{r mv_model_ppc}
model_mv_ppc <- function(){
  for(k in 1:N_polls){
    y[k] ~ dnorm(p[k],1/sigma2_y[r[k]]) #note no longer binomial
    p[k] = theta[r[k],t[k]]
  }
  for(j in 2:N_days){
    theta[1:N_states,j] ~ dmnorm(theta[1:N_states,j-1],Phi)
    res[1:N_states,j] = theta[1:N_states,j] - theta[1:N_states,j-1]
    theta.new[1:N_states,j] ~ dmnorm(theta[1:N_states,j-1],Phi)
    res.new[1:N_states,j] = theta.new[1:N_states,j] - theta.new[1:N_states,j-1]
  }
  fit[1:N_states,] <- sum(res[1:N_states,])
  fit.new[1:N_states,] <- sum(res.new[1:N_states,])
  Phi ~ dwish(states_corr_mat,N_states+1) #fill in wishart parameters, google JAGS wishart distribution should turn it up
  

  #Use your hierarhciacl prior for sigma2_y from before 
  for(j in 1:N_states){
      mu0[j] ~ dnorm(priors[j],pow(7.5,-2))
      sigma2_y[j] = 1/sigma2_y_inv[j]
      sigma2_y_inv[j] ~ dgamma(nu_y,nu_y*tau_y) 
      theta[j,1] ~ dnorm(mu0[j],pow(sigma2_0,-1))
  }
  nu_y ~ dunif(0,100)
  tau_y ~ dunif(0,100)
  
  nu_beta ~ dunif(0,100)
  tau_beta ~ dunif(0,100)
  
  sigma2_0 = 1/sigma2_0_inv
  sigma2_0_inv ~ dgamma(.5,.5)

}
```

```{r eval=F}
# Using original correlation matrix (DOESN'T WORK)

state_correlation_matrix = read.csv("us-potus-model-master/data/state_correlation_matrix.csv")

dex_states_inc = NULL
for (st in states) {
  new_dex = which(colnames(state_correlation_matrix)==st)
  dex_states_inc = c(dex_states_inc, new_dex)
}

inc_states_corr_matrix = state_correlation_matrix[c(dex_states_inc),c(dex_states_inc)]
```

```{r}
# Using FULL original correlation matrix

state_correlation_matrix = read.csv("states_cov_matrix_full.csv")
state_correlation_matrix = state_correlation_matrix %>% select(-("state"))

dex_states_inc = NULL
for (st in states) {
  new_dex = which(colnames(state_correlation_matrix)==st)
  dex_states_inc = c(dex_states_inc, new_dex)
}

states_cov_matrix = state_correlation_matrix[c(dex_states_inc),c(dex_states_inc)]
```


```{r eval=F}
states_cov_matrix = read.csv("states_cov_matrix.csv", header = TRUE)[,-1]
```

```{r}
jags_data$states_corr_mat <- states_cov_matrix
set.seed(6)  
jags_sims_mv_ppc <- jags(data = jags_data, model.file = model_mv_ppc , parameters.to.save = c("theta","Sigma","p","sigma2_y","res","fit","fit.new"),
  n.chains = 3,
            n.adapt = 100,
            n.iter = 10000,
            n.burnin = 4000,
            n.thin = 2)
```

```{r ppc}
pp.check(jags_sims_mv_ppc, observed = 'fit', simulated = 'fit.new')
```

```{r residual plots}
require(reshape2)
Result_MCMC <- as.mcmc(jags_sims_mv_ppc)
Result_data <- data.frame(as.matrix(Result_MCMC))
  ResidualName <- seq(1, N_states)
for( idx in 1:N_states)
{
  ResidualName[idx] <- capture.output(cat( c("res", idx, ""), sep = "."))
}
residul_check <- Result_data[, ResidualName]
ggplot(data = melt(residul_check), aes(x=variable, y=value)) + scale_x_discrete(breaks = c()) + geom_boxplot(aes(fill=variable), outlier.size = 0.1) + theme(legend.position = "none") + labs(y = "Residuals", x = "Observation", title = "Boxplot of Residuals")
```

