---
title: "first_model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r pressure, echo=FALSE, message=F, warning=F}
library(lubridate)
library(tidyverse)
library(R2jags)
library(gridExtra)
```

## Data

```{r eval=F}

pres_polls = read.csv("president_polls.csv")


dem_results = pres_polls[pres_polls$candidate_party == "DEM",]
dem_cols = colnames(dem_results)
cols_to_paste = (length(dem_cols)-3):length(dem_cols)
dem_cols[cols_to_paste] = paste(dem_cols[cols_to_paste], "DEM", sep="_")
colnames(dem_results) = dem_cols

rep_results = pres_polls[pres_polls$candidate_party == "REP",]
rep_cols = colnames(rep_results)
rep_cols[cols_to_paste] = paste(rep_cols[cols_to_paste], "REP", sep="_")
colnames(rep_results) = rep_cols

rep_small = rep_results %>% select(question_id, candidate_id_REP, candidate_name_REP, pct_REP)

final_polls = left_join(dem_results, rep_small, by="question_id")

final_polls = final_polls[!duplicated(final_polls$poll_id),]


final_polls$days_to_election = as.numeric(as.Date("11/3/2020", "%m/%d/%y")-as.Date(final_polls$end_date, "%m/%d/%y"))

final_polls$state = as.character(final_polls$state)

final_polls$votes_DEM = round( (final_polls$pct_DEM/100) * final_polls$sample_size)
final_polls$votes_REP = round( (final_polls$pct_REP/100) * final_polls$sample_size)

final_polls = final_polls %>% mutate(y = votes_DEM/(votes_DEM + votes_REP)*100)


final_polls = final_polls %>%
  mutate(state = ifelse(state == "","US",state))

states_raw = read.csv("electoral_votes.csv")
states_raw$state = states_raw$State

final_polls = merge(final_polls, states_raw, by="state", all.x=T)
final_polls$Abbrev = as.character(final_polls$Abbrev)
final_polls$Abbrev = replace_na(final_polls$Abbrev, "US")
final_polls$state = final_polls$Abbrev

econ_pres_polls = final_polls
saveRDS(econ_pres_polls, "cleaned_pres_polls.rds")
```

```{r }

econ_pres_polls = read.csv("2020 US presidential election polls - all_polls.csv")

econ_pres_polls$end.date = as.character(econ_pres_polls$end.date)

econ_pres_polls = econ_pres_polls %>%
  mutate(end.date = case_when(
    end.date == "108/2020" ~ "10/8/2020",
    TRUE ~ end.date
  ))

econ_pres_polls$days_to_election = as.numeric(as.Date("11/3/2020", "%m/%d/%y")-as.Date(econ_pres_polls$end.date, "%m/%d/%y"))

econ_pres_polls$state = as.character(econ_pres_polls$state)

econ_pres_polls = econ_pres_polls %>%
  mutate(state = ifelse(state == "--","US",state),
         y = biden/(biden + trump)*100)

```

```{r}
econ_pres_polls = econ_pres_polls %>%
  filter(days_to_election <= 60)

states_of_interest = c("MN", "NH", "MI", "WI", "PA", "NV", "FL", "AZ", "NC", "GA", "IA", "OH", "TX")

econ_pres_polls= econ_pres_polls %>% filter(state %in% states_of_interest)
saveRDS(econ_pres_polls, "cleaned_econ_polls.rds")
```

```{r}
states <- sort(econ_pres_polls$state %>% unique)

y <- econ_pres_polls$y
r <- match(econ_pres_polls$state,states)
t <- econ_pres_polls$days_to_election + 1 #WHY PLUS ONE?

N_polls <- y %>% length
N_states <- states %>% length
N_days <- t %>% max

# calculate partisan lean part of the prior
#leans_allstates = read.csv("partisan_leans.csv")
leans_allstates = read.csv("partisan_leans_538.csv")
leans_states = NULL
for (st in states) {
  new_lean = leans_allstates[leans_allstates$Abbrev==st, "Lean"]
  leans_states = c(leans_states, new_lean)
}

lean_to_prior = function(lean) {
  return(50 + (1/2)*lean)
}

# calculate the fundamentals part of the prior
# read in abramowitz data
# abramowitz <- read.csv('abramowitz_data.csv') 
# prior_model <- lm(incvote ~  juneapp + q2gdp, data = abramowitz)

# read in abramowitz_additional data
abramowitz <- read.csv('abramowitz_additional.csv') 
prior_model <- lm(incvote ~  juneapp + three_month_stock_growth + q2_real_income_growth, data = abramowitz)

# make predictions (for 2020, g2gdp = -9.1, juneapp = -10)
# keep sources for this! https://www.bea.gov/news/glance
# the predict() alone is for incumbent, so we do 100 - for Biden 
# with juneapp + q2gdp as predictors 
# national_mu_prior <- 100 - predict(prior_model,newdata = tibble(q2gdp = -31.4, juneapp = -10))

# with juneapp + three_month_stock_growth + q2_real_income_growth as predictors
### need to update on stock data on Nov 1 ###
national_mu_prior <- 100 - predict(prior_model,newdata = tibble(juneapp = -10, three_month_stock_growth = -0.0280759, q2_real_income_growth = 11.8))

# on correct scale
# national_mu_prior <- national_mu_prior / 100
# Mean of the mu_b_prior
# mu_b_prior <- logit(national_mu_prior + prior_diff_score)
# # or read in priors if generated already
# prior_in <- read_csv("data/state_priors_08_12_16.csv") %>%
#   filter(date <= RUN_DATE) %>%
#   group_by(state) %>%
#   arrange(date) %>%
#   filter(date == max(date)) %>%
#   select(state,pred) %>%
#   ungroup() %>%
#   arrange(state)


```


```{r final-prior-calculation}
# because partisan lean is in terms of democ
priors = 0.1*national_mu_prior + 0.9*lean_to_prior(leans_states)

jags_data <- list(y=y,t=t,r=r,
                  N_polls=N_polls,N_states=N_states,N_days=N_days,
                  priors=priors)
```


# Model with multivariate formulation

```{r mv_model}
model_mv <- function(){
  for(k in 1:N_polls){
    y[k] ~ dnorm(p[k],1/sigma2_y[r[k]]) #note no longer binomial
    p[k] = theta[r[k],t[k]]
  }
  for(j in 2:N_days){
    theta[1:N_states,j] ~ dmnorm(theta[1:N_states,j-1],Phi)
  }
  
  
  Phi ~ dwish(states_corr_mat,N_states+1) #fill in wishart parameters, google JAGS wishart distribution should turn it up
  Sigma = inverse(Phi)
  #which, Phi or Sigma is the covariance and which is the precision? 
  
  #optional: theta[1:N_states,1] ~ dmnorm(mu0,s0) #define mu0 and s0 in your jags_data object
  
  #Use your hierarhciacl prior for sigma2_y from before 
  for(j in 1:N_states){
      mu0[j] ~ dnorm(priors[j],pow(7.5,-2))

      sigma2_y[j] = 1/sigma2_y_inv[j]
      sigma2_y_inv[j] ~ dgamma(nu_y,nu_y*tau_y) 
      
      theta[j,1] ~ dnorm(mu0[j],pow(sigma2_0,-1))
  }
  nu_y ~ dunif(0,100)
  tau_y ~ dunif(0,100)
  
  nu_beta ~ dunif(0,100)
  tau_beta ~ dunif(0,100)
  
  sigma2_0 = 1/sigma2_0_inv
  sigma2_0_inv ~ dgamma(.5,.5)
}
```

```{r eval=F}
# Using original correlation matrix (DOESN'T WORK)

state_correlation_matrix = read.csv("us-potus-model-master/data/state_correlation_matrix.csv")

dex_states_inc = NULL
for (st in states) {
  new_dex = which(colnames(state_correlation_matrix)==st)
  dex_states_inc = c(dex_states_inc, new_dex)
}

inc_states_corr_matrix = state_correlation_matrix[c(dex_states_inc),c(dex_states_inc)]
```

```{r}
# Using FULL original correlation matrix

state_correlation_matrix = read.csv("states_cov_matrix_full.csv")
state_correlation_matrix = state_correlation_matrix %>% select(-("state"))

dex_states_inc = NULL
for (st in states) {
  new_dex = which(colnames(state_correlation_matrix)==st)
  dex_states_inc = c(dex_states_inc, new_dex)
}

states_cov_matrix = state_correlation_matrix[c(dex_states_inc),c(dex_states_inc)]
```


```{r eval=F}
# states_cov_matrix = as.matrix(read.csv("states_cov_matrix - Sheet1.csv", header = TRUE)[,-1], nrow = 19, byrow = TRUE)
# isSymmetric(states_cov_matrix)
# 
# for (r in 1:19) {
#   for (c in 1:19) {
#     if (states_cov_matrix[r,c] != states_cov_matrix[c,r]) {
#       states_cov_matrix[r,c] = states_cov_matrix[c,r]
#     }
#   }
# }
# 
# isSymmetric(states_cov_matrix)
# states_cov_matrix == t(states_cov_matrix)
# 
# write.csv(states_cov_matrix, "states_cov_matrix.csv")

states_cov_matrix = read.csv("states_cov_matrix.csv", header = TRUE)[,-1]

#states_cov_matrix == t(states_cov_matrix)
#eigen(states_cov_matrix)
```

```{r}
jags_data$states_corr_mat <- states_cov_matrix

#jags_data$states_corr_mat <- diag(N_states)#test_matrix

#library(lqmm)
#test_matrix = make.positive.definite(inc_states_corr_matrix)
#eigen(inc_states_corr_matrix)
#eigen(test_matrix)

#be sure to add your added parameters to parameters.to.save
jags_sims_mv <- jags(data = jags_data,model.file = model_mv, parameters.to.save = c("theta","Sigma","p","sigma2_y"),
n.iter = 10000)

#jags_sims_mv
```


## Not required: Probability of Biden Win by State

```{r}
elec_sims <- jags_sims_mv$BUGSoutput$sims.list$theta[,,1]
colnames(elec_sims) <- states
(elec_sims>50) %>% colMeans() #P(Biden Win) each state

#elec_sims <- jags_sims$BUGSoutput$sims.list$beta[,,1]
#colnames(elec_sims) <- states
#(elec_sims>50) %>% colMeans() #P(Biden Win) each state

#in other states: Biden: 232-13, Trump: 306-29-18-15-10-20
#b_ex_votes <- 232-13; t_ex_votes <- 306-29-18-15-10-20
```


## Probability Trump Wins Re-Election

```{r}
elec_votes_df = read.csv("electoral_votes.csv")

blue_EVs_2016 = sum(elec_votes_df$EV*elec_votes_df$blue2016) + 3 # DC
safe_blue_2020 = blue_EVs_2016  ## Will subtract states in model

ec_bystate = c()

for (st in states) {
  st_EVs = elec_votes_df[elec_votes_df$Abbrev==st,"EV"]
  ec_bystate = c(ec_bystate, st_EVs)
  
  if (elec_votes_df[elec_votes_df$Abbrev==st,"blue2016"] == 1) {
    safe_blue_2020 = safe_blue_2020 - st_EVs
  }
}

#ec_bystate = c(3, 9, 11, 55, 9, 3, 29, 16, 4, 6, 4, 11, 6, 8, 8, 11, 10, 4, 16, 10, 10, 6, 3, 15, 3, 4, 14, 5, 6, 29, 18, 7, 7, 20, 9, 3, 38, 0, 6, 11, 3, 12, 10, 5 )

ec_votes_inc_states <- ((elec_sims>50) %*% diag(ec_bystate)) %>% rowSums() #+ 232

ec_votes_dem = ec_votes_inc_states+safe_blue_2020 #anything else Biden should win (CT, Hawaii, IL, RI, DC)

# anything else for Trump (6 Arkansas, 5 Nebraska, 11 Tennessee, 3 S Dakota, 3 Wyoming) 

p_trump_win = 1 - mean(ec_votes_dem >= 270)
p_trump_win
```


## Bonus stuff: Dem EC Vote Histogram and Win Prob.

```{r}
hist(ec_votes_dem)

#pmean = ec_votes>=270
mean(ec_votes_dem>=270) 
#print(c(quantile(pmean, 0.025), quantile(pmean, 0.975)))
```

# Traceplots

```{r}
betas_day_of_election = sapply(1:N_states, function(i) {paste0("theta.", i, ".1.")} )
parameters = c(betas_day_of_election)

tp_vars = data.frame(jags_sims_mv$BUGSoutput$sims.matrix)[,parameters]

tps <- function(var){
  ggplot(tp_vars, aes_(y=as.name(var), x=seq(1,nrow(tp_vars)))) +
    geom_line() +
    labs(x ="Iterations", y = as.name(var))
}

all_beta_trace = lapply(names(tp_vars), tps)
do.call(grid.arrange, all_beta_trace)
```

