---
title: "who_votes_eda"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r}
library(tidyverse)
```
## Merging Data

```{r}
voter_small = readRDS("ncvoter_Statewide_small.rds") %>%
  mutate(voter_reg_num = str_remove(voter_reg_num, "^0+")) 
  
voter_small$voter_reg_num[which(voter_small$voter_reg_num=="")] <- 0

voter_small = voter_small %>%
  mutate(unique_id = paste(county_desc, voter_reg_num, sep = "_"))

hist_small = readRDS("ncvhis_Statewide_small.rds") %>%
  mutate(unique_id = paste(county_desc, voter_reg_num, sep = "_"))

voter_small[which(voter_small$voter_reg_num=="")] <- 0
voter_hist = merge(voter_small, hist_small, by = "unique_id", all.y = TRUE)

```

```{r}
voter_small_samp = sample_n(voter_small, 1000000) 
hist_small_samp = sample_n(hist_small, 1000000) 
merge_small_samp = sample_n(voter_hist, 1000000) 
# TODO filter the data set and only leaves the 2016 data points to focus on the presidential election year
# TODO mapping individuals to 13 districts if NA cong_dist_abbrv
# TODO remove weird birth dates and overlapping districts
```

```{r}
density_age_party <- ggplot(merge_small_samp, aes(birth_age,color=voted_party_cd)) + labs(y="Density", x = "Age", title = "Marginal Density for Ages \n of Different Party Voters", caption = "Figure 1") + geom_density(alpha=.5)  +theme(plot.title = element_text(hjust = 0.5))
stacked_race_party <- ggplot(merge_small_samp, aes(race_code,fill=voted_party_cd)) + labs(y="Density", x = "Age", title = "Race v. Party", caption = "Figure 1")+ geom_bar( position="fill", stat="count") + theme(plot.title = element_text(hjust = 0.5))
stacked_county_party <- ggplot(merge_small_samp, aes(county_id.x,fill=voted_party_cd)) + labs(y="Density", x = "County", title = "County v. Party", caption = "Figure 1")+ geom_bar( position="fill", stat="count") + theme(plot.title = element_text(hjust = 0.5))
stacked_county_race <- ggplot(merge_small_samp, aes(county_id.x,fill=race_code)) + labs(y="Density", x = "County", title = "County v. Race", caption = "Figure 1")+ geom_bar( position="fill", stat="count") + theme(plot.title = element_text(hjust = 0.5))
stacked_state_race <- ggplot(merge_small_samp, aes(birth_state,fill=race_code)) + labs(y="Density", x = "Birth State", title = "Birth State v. Race", caption = "Figure 1")+ geom_bar( position="fill", stat="count") + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
box_age_race <- ggplot(merge_small_samp, aes(x=race_code, y=birth_age)) + geom_boxplot() + labs(y="Age", x = "Race", title = "Age v. Races", caption = "Figure 2")  +theme(plot.title = element_text(hjust = 0.5)) 
```

